name: Build and Test
on:
  push:
    paths-ignore:
      - '**.md'

# only one build per branch
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.10.1']
        cabal: ['3.10.3.0']
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies - Linux
        if: runner.os == 'Linux'
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install libpcre3-dev
          sudo apt-get install libmysqlclient-dev
          sudo apt-get install libmysqlclient21
          echo $LIBMYSQL_PLUGIN_DIR
          sudo ln -s /opt/hostedtoolcache/mysql/9.0.1/x64/lib/libmysqlclient.so.24 /usr/lib/libmysqlclient.so.24

      - name: Setup - PostgreSQL
        id: postgres-setup
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: "16"
          database: 'postgres'
          username: 'postgres'
          password: ${{ env.PGPASSWORD }}

      - name: Setup - MySQL
        id: mysql-setup
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "9.0.1"

      - name: Setup - GHC ${{ matrix.ghc }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          # Defaults, added for clarity:
          cabal-version: ${{ matrix.cabal }}
          cabal-update: true

      - name: Build - Configure
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Build - Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Build - Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cabal build mysql --extra-include-dirs=/opt/homebrew/include
          cabal build all --only-dependencies --extra-include-dirs=/opt/homebrew/include

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Build - Save dependencies to cache
        uses: actions/cache/save@v4
        # If we had an exact cache hit, trying to save the cache would error because of key clash.
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all --extra-include-dirs=/opt/homebrew/include

      - name: Test
        env:
          PGSERVICE: ${{ steps.postgres-setup.outputs.service-name }}
          MYSQL_STUFF: ${{ steps.mysql.outputs.base-dir }}
        run: |
          set -x
          export MYSQL_UNIX_PORT=$(dirname $MYSQL_HOME)/tmp/mysql.sock
          cabal run emulator-tests

      # We run this only when a PR is merged so we can see how things are performing
      # on the GH actions machines.
      - name: Benchmark
        if: github.ref == 'refs/heads/main'
        run: cabal run emulator-tests
