name: Build static binary
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main

# only one build per branch
concurrency:
  group: static-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build static binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Docker build
        run: ./utils.sh build-docker
